<table>
<thead>
<tr>
<th>Name</th>
<th>Gender</th>
<th>Phone</th>
<th>Email</th>
<th>Address</th>
<th>Nationality</th>
<th>DOB</th>
<th>Education</th>
<th>Preffered_Contact</th>
</tr>
</thead>
<tbody>
@if($data['name']!='')
    <tr>
    <td>{{$data['name']}}</td>
    <td>{{$data['gender']}}</td>
    <td>{{$data['phone']}}</td>
    <td>{{$data['email']}}</td>
    <td>{{str_replace(",","-",$data['address'])}}</td>
    <td>{{$data['nationality']}}</td>
    <td>{{$data['dob']}}</td>
    <td>{{$data['education']}}</td>
    <td>{{$data['preffered_mode']}}</td>
    </tr>
@endif
</tbody>
</table>